name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USER }}
          password: ${{ secrets.GIT_TOKEN }}
      - name: Build Container Image
        run: docker/build-push-action@v2
        with:
          context: ./weewx-rtldavis
          file: ./weewx-rtldavis/dockerfile
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ env.GIT_REF }}
            ${{ env.IMAGE }}:${{ env.GIT_SHA }}
            ${{ env.IMAGE }}:${{ env.BUILD_VER }}
          push: true
