name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # - name: add build args
      #   id: args
      #   shell: bash
      #   run: |
      #     echo "::set-output name=amd64::BUILD_FROM=$(jq -r '.build_from.amd64  // empty' ${{ steps.information.outputs.build }})"
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Container Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./weewx-rtldavis
          file: ./weewx-rtldavis/dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/weewx-rtldavis:latest